# Site settings
title: Dr. Ueli Reber - Computational social scientist
tag_text: Ueli Reber
description: Dr. Ueli Reber - Computational social scientist
url: ""
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
